linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - revive
  disable:
    - lll
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/veiloq/zlmd
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/ 